use_frameworks!

platform :ios, '9.0'

target 'ZQKeyboardEmotionView_Example' do
  pod 'ZQKeyboardEmotionView', :path => '../'

  target 'ZQKeyboardEmotionView_Tests' do
    inherit! :search_paths

    
  end
end
